### ISSUE TITLE
Errors when enabling plugin

### ISSUE THREAD

**Issue by spirrello** [MatthewC/yourls-password-protection#8]
When I click `Activate` I'm getting the following error.

```
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, 
null given in /var/www/html/user/plugins/password-protection/plugin.php:33 
Stack trace: #0 /var/www/html/includes/functions-plugins.php(232): warning_redirection(Array) 
#1 /var/www/html/includes/functions-plugins.php(282): yourls_apply_filter('pre_redirect', Array, true) 
#2 /var/www/html/includes/functions.php(217): yourls_do_action('pre_redirect', 'http://supertes...', 302) 
#3 /var/www/html/admin/plugins.php(26): yourls_redirect('http://supertes...', 302) 
#4 {main} thrown in /var/www/html/user/plugins/password-protection/plugin.php on line 33
```

**Comment by spirrello** [comment]
fixed with #9
